services:
  - type: worker
    name: video-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_IDS
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: PHONE_NUMBER
        sync: false
      - key: FIREBASE_DATABASE_URL
        sync: false
      - key: FIREBASE_CREDENTIALS_JSON
        sync: false
